defaults:
  - _aucurriculum_train_
  - _self_

results_dir: ../results
experiment_id: cifar
training_type: step
iterations: 156250 # 50 epochs in total
eval_frequency: 3125 # 1 epoch
save_frequency: 3125

hydra:
  sweeper:
    params:
      +seed: 1
      +batch_size: 16
      +learning_rate: 0.01, 0.001, 0.0001
      dataset: CIFAR-10
      model: EfficientNet-B0, EfficientNet-B0-T, EfficientNet-B4, EfficientNet-B4-T, ResNet-50, ResNet-50-T
      optimizer: Adam, SGD-M9, SAM-SGD-M9
      curriculum: None
      curriculum/sampling: None
      curriculum/scoring: None
      curriculum/pacing: None
      curriculum.pacing.initial_size: 1
      curriculum.pacing.final_iteration: 0