defaults:
  - _aucurriculum_train_
  - _self_

results_dir: ../results
experiment_id: dcase
training_type: step
iterations: 43650 # 50 epochs in total
eval_frequency: 873 # 1 epoch
save_frequency: 873

hydra:
  sweeper:
    params:
      +seed: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
      +batch_size: 16
      +learning_rate: 0.01
      dataset: DCASE2020Task1A-32k
      model: EfficientNet-B0
      optimizer: SAM-SGD-M9
      curriculum: None
      curriculum/sampling: None
      curriculum/scoring: None
      curriculum/pacing: None
      curriculum.pacing.initial_size: 1
      curriculum.pacing.final_iteration: 0