id: CELoss-CNN10-T
type: CELoss
_target_: aucurriculum.curricula.scoring.CELoss
run_name: DCASE2020Task1A-32k_Cnn10-32k-T_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_1
criterion: autrainer.criterions.CrossEntropyLoss
stop: best
subset: train
