id: CumAcc-SGD-0.001
type: CumulativeAccuracy
_target_: aucurriculum.curricula.scoring.CumulativeAccuracy
run_name: DCASE2020Task1A-32k_EfficientNet-B0_SGD-M9_0.001_16_step_43650_None_None_N_N_None_None_1_0_1
stop: best
subset: train
