id: CVLoss-S1
type: CVLoss
_target_: aucurriculum.curricula.scoring.CVLoss
splits: 3
setup:
  filters: null
  dataset: DCASE2020Task1A-32k
  model: EfficientNet-B0
  optimizer: SAM-SGD-M9
  learning_rate: 0.01
  scheduler: None
  augmentation: None
  seed: 1
  batch_size: 16
  inference_batch_size: 16
  plotting: Default
  training_type: step
  iterations: 21825
  eval_frequency: 873
  save_frequency: 21825
  save_train_outputs: true
  save_dev_outputs: true
  save_test_outputs: true
criterion: autrainer.criterions.CrossEntropyLoss
stop: best
subset: train
