id: FIT-Adam-0.01
type: FirstIteration
_target_: aucurriculum.curricula.scoring.FirstIteration
run_name: DCASE2020Task1A-32k_EfficientNet-B0_Adam_0.01_16_step_43650_None_None_N_N_None_None_1_0_1
stop: best
subset: train
