id: PD-Model
type: PredictionDepth
_target_: aucurriculum.curricula.scoring.PredictionDepth
run_name:
- DCASE2020Task1A-32k_EfficientNet-B0_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_1
- DCASE2020Task1A-32k_EfficientNet-B0-T_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_1
- DCASE2020Task1A-32k_Cnn10_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_1
- DCASE2020Task1A-32k_Cnn10-32k-T_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_1
- DCASE2020Task1A-32k_Cnn14_SAM-SGD-M9_0.001_16_step_43650_None_None_N_N_None_None_1_0_1
- DCASE2020Task1A-32k_Cnn14-32k-T_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_1
stop: best
subset: train
max_embedding_size: 8192
match_dimensions: true
probe_placements:
  DCASE2020Task1A-32k_EfficientNet-B0_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_1:
  - model_features_0_1
  - model_features_1_0_block_2_1
  - model_features_\d_0_block_3_1
  - add(_\d+)?
  - model_features_8_1
  DCASE2020Task1A-32k_EfficientNet-B0-T_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_1:
  - model_features_0_1
  - model_features_1_0_block_2_1
  - model_features_\d_0_block_3_1
  - add(_\d+)?
  - model_features_8_1
  DCASE2020Task1A-32k_Cnn10_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_1:
  - transpose_1
  - conv_block\d_bn1
  - conv_block\d_bn2
  - fc1
  DCASE2020Task1A-32k_Cnn10-32k-T_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_1:
  - transpose_1
  - conv_block\d_bn1
  - conv_block\d_bn2
  - fc1
  DCASE2020Task1A-32k_Cnn14_SAM-SGD-M9_0.001_16_step_43650_None_None_N_N_None_None_1_0_1:
  - transpose_1
  - conv_block\d_bn1
  - conv_block\d_bn2
  - fc1
  DCASE2020Task1A-32k_Cnn14-32k-T_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_1:
  - transpose_1
  - conv_block\d_bn1
  - conv_block\d_bn2
  - fc1
