id: PD-S1+2+3+4+5
type: PredictionDepth
_target_: aucurriculum.curricula.scoring.PredictionDepth
run_name:
- DCASE2020Task1A-32k_EfficientNet-B0_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_1
- DCASE2020Task1A-32k_EfficientNet-B0_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_2
- DCASE2020Task1A-32k_EfficientNet-B0_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_3
- DCASE2020Task1A-32k_EfficientNet-B0_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_4
- DCASE2020Task1A-32k_EfficientNet-B0_SAM-SGD-M9_0.01_16_step_43650_None_None_N_N_None_None_1_0_5
stop: best
subset: train
max_embedding_size: 8192
match_dimensions: true
probe_placements:
- model_features_0_1
- model_features_1_0_block_2_1
- model_features_\d_0_block_3_1
- add(_\d+)?
- model_features_8_1
