id: CELoss-S1+2
type: CELoss
_target_: aucurriculum.curricula.scoring.CELoss
run_name:
- CIFAR-10_EfficientNet-B0_Adam_0.001_16_step_156250_None_None_N_N_None_None_1_0_1
- CIFAR-10_EfficientNet-B0_Adam_0.001_16_step_156250_None_None_N_N_None_None_1_0_2
criterion: autrainer.criterions.CrossEntropyLoss
stop: best
subset: train
