id: CELoss-Adam-0.01
type: CELoss
_target_: aucurriculum.curricula.scoring.CELoss
run_name: CIFAR-10_EfficientNet-B0_Adam_0.01_16_step_156250_None_None_N_N_None_None_1_0_1
criterion: autrainer.criterions.CrossEntropyLoss
stop: best
subset: train
