id: CumAcc-SGD-0.01
type: CumulativeAccuracy
_target_: aucurriculum.curricula.scoring.CumulativeAccuracy
run_name: CIFAR-10_EfficientNet-B0_SGD-M9_0.01_16_step_156250_None_None_N_N_None_None_1_0_1
stop: best
subset: train
