id: CumAcc-S11+12+13+14+15
type: CumulativeAccuracy
_target_: aucurriculum.curricula.scoring.CumulativeAccuracy
run_name:
- CIFAR-10_EfficientNet-B0_Adam_0.001_16_step_156250_None_None_N_N_None_None_1_0_11
- CIFAR-10_EfficientNet-B0_Adam_0.001_16_step_156250_None_None_N_N_None_None_1_0_12
- CIFAR-10_EfficientNet-B0_Adam_0.001_16_step_156250_None_None_N_N_None_None_1_0_13
- CIFAR-10_EfficientNet-B0_Adam_0.001_16_step_156250_None_None_N_N_None_None_1_0_14
- CIFAR-10_EfficientNet-B0_Adam_0.001_16_step_156250_None_None_N_N_None_None_1_0_15
stop: best
subset: train
