id: CumAcc-R50
type: CumulativeAccuracy
_target_: aucurriculum.curricula.scoring.CumulativeAccuracy
run_name: CIFAR-10_ResNet-50_Adam_0.001_16_step_156250_None_None_N_N_None_None_1_0_1
stop: best
subset: train
